Config = {
    Chains = {
        ["otfchain"] = {
            componentId = 7,
            drawableId = 15,
            textureId = 0,
            paletteId = 2,
        },
        ["cubanchain"] = {
            componentId = 7,
            drawableId = 4,
            textureId = 0,
            paletteId = 2,
        },
        ["crosschain"] = {
            componentId = 7,
            drawableId = 3,
            textureId = 0,
            paletteId = 2,
        },
        ["diamondchainv"] = {
            componentId = 7,
            drawableId = 7,
            textureId = 0,
            paletteId = 2,
        },
        ["holster"] = {
            componentId = 7,
            drawableId = 8,
            textureId = 0,
            paletteId = 2,
        },
        ["woochain"] = {
            componentId = 7,
            drawableId = 13,
            textureId = 0,
            paletteId = 2,
        },
        ["ratchain"] = {
            componentId = 7,
            drawableId = 14,
            textureId = 0,
            paletteId = 2,
        },
        ["cubanmafiachain"] = {
            componentId = 7,
            drawableId = 10,
            textureId = 0,
            paletteId = 2,
        },
        ["gthreechain"] = {
            componentId = 7,
            drawableId = 11,
            textureId = 0,
            paletteId = 2,
        },
        ["spadeschain"] = {
            componentId = 7,
            drawableId = 12,
            textureId = 0,
            paletteId = 2,
        },
        ["woochaintwo"] = {
            componentId = 7,
            drawableId = 9,
            textureId = 0,
            paletteId = 2,
        },
    },
    Masks = {
        ["skullmask"] = {
            componentId = 1,
            drawableId = 2,
            textureId = 0,
            paletteId = 2,
        },
        ["monkeymask"] = {
            componentId = 1,
            drawableId = 3,
            textureId = 0,
            paletteId = 2,
        },
        ["balaclava"] = {
            componentId = 1,
            drawableId = 229,
            textureId = 0,
            paletteId = 2,
        },
        ["scarecrowmask"] = {
            componentId = 1,
            drawableId = 261,
            textureId = 0,
            paletteId = 2,
        },
        ["terrorwit"] = {
            componentId = 1,
            drawableId = 1,
            textureId = 0,
            paletteId = 2,
        },	
        ["hockeymask"] = {
            componentId = 1,
            drawableId = 4,
            textureId = 0,
            paletteId = 2,
        },	
        ["sok"] = {
            componentId = 1,
            drawableId = 224,
            textureId = 0,
            paletteId = 2,
        },	
        ["clown"] = {
            componentId = 1,
            drawableId = 287,
            textureId = 0,
            paletteId = 2,
        },	
        ["noselong"] = {
            componentId = 1,
            drawableId = 204,
            textureId = 0,
            paletteId = 2,
        },	
        ["tshirtmask"] = {
            componentId = 1,
            drawableId = 246,
            textureId = 0,
            paletteId = 2,
        },	
        ["zak"] = {
            componentId = 1,
            drawableId = 241,
            textureId = 0,
            paletteId = 2,
        },	
        ["gorilla"] = {
            componentId = 1,
            drawableId = 288,
            textureId = 0,
            paletteId = 2,
        },	
        ["paard"] = {
            componentId = 1,
            drawableId = 289,
            textureId = 0,
            paletteId = 2,
        },	
        ["paardu"] = {
            componentId = 1,
            drawableId = 290,
            textureId = 0,
            paletteId = 2,
        },	
        ["skullr"] = {
            componentId = 1,
            drawableId = 291,
            textureId = 0,
            paletteId = 2,
        },	
	
	},
    Shoes = {
        ["nikefoamposites"] = {
            componentId = 6,
            drawableId = 10,
            textureId = 0,
            paletteId = 2,
        },
        ["nikefoamposites1"] = {
            componentId = 6,
            drawableId = 10,
            textureId = 1,
            paletteId = 2,
        },
        ["nikefoamposites2"] = {
            componentId = 6,
            drawableId = 10,
            textureId = 2,
            paletteId = 2,
        },
        ["jordan6s"] = {
            componentId = 6,
            drawableId = 1,
            textureId = 0,
            paletteId = 2,
        },
        ["jordan6s1"] = {
            componentId = 6,
            drawableId = 1,
            textureId = 1,
            paletteId = 2,
        },
        ["jordan6s2"] = {
            componentId = 6,
            drawableId = 1,
            textureId = 2,
            paletteId = 2,
        },
        ["jordan11s"] = {
            componentId = 6,
            drawableId = 15,
            textureId = 0,
            paletteId = 2,
        },
        ["jordan11s1"] = {
            componentId = 6,
            drawableId = 15,
            textureId = 1,
            paletteId = 2,
        },
        ["jordan11s2"] = {
            componentId = 6,
            drawableId = 15,
            textureId = 2,
            paletteId = 2,
        },
    },
    Hats = {
        ["buckethat"] = {
            componentId = 5,
            drawableId = 3,
            textureId = 1,
            paletteId = 2,
        },
        ["santahat"] = {
            componentId = 5,
            drawableId = 22,
            textureId = 0,
            paletteId = 2,
        },
    },
    Glasses = {
        ["glasses"] = {
            componentId = 0,
            drawableId = 2,
            textureId = 0,
            paletteId = 2,
        },
        ["glasses1"] = {
            componentId = 0,
            drawableId = 3,
            textureId = 0,
            paletteId = 2,
        },
    },
    Watches = {
        ["shinywatch"] = {
            componentId = 8,
            drawableId = 0,
            textureId = 0,
            paletteId = 2,
        },
    },
}